### ISSUE TITLE
Challenge roadmap

### ISSUE THREAD

**Issue by csubira** [csubira/tcp#2]
## Development
- [ ] Readme.md and documentation https://github.com/csubira/tcp/issues/3
- [ ] Set development environment https://github.com/csubira/tcp/issues/4
- [ ] Clean and define library https://github.com/csubira/tcp/issues/7
- [ ] Add new tests https://github.com/csubira/tcp/issues/5
- [ ] Add storage https://github.com/csubira/tcp/issues/6

_Optionals:_
- Github releases

## CI/CD
- [ ] Configure continuous integration tool https://github.com/csubira/tcp/issues/8

## Production

- [ ] Put app into production https://github.com/csubira/tcp/issues/9
- [ ] Description of basic security settings https://github.com/csubira/tcp/issues/10

_Optionals:_ 

- Parallel processing
- Reproducible provisioning

## Metrics

- [ ] Add metrics https://github.com/csubira/tcp/issues/11

-------------------
_Extra:_
- Web server
